baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Robert Duchey'
theme = 'rd'
paginate = 3

[params]
  brief = 'A blog about things'
  paginate = 3

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = -10
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = -8
[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = -6

